name: Trigger Test (product → EC2)

on:
  push:
    branches:
      - product

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Who am I?
        run: |
          echo "Running on EC2 Self-hosted Runner"
          hostname
          whoami
